name: boot image dumper

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM URL'
        required: true
        default: ' '
      BOOT_NAME:
        description: 'BOOT IMAGE  NAME'
        required: true
        default: 'boot.img'
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v3
    - name: Dump boot
      run: |
        cd ~
        sudo apt install aria2
        git clone https://github.com/vm03/payload_dumper --depth=1 dumper &&cd dumper &&pip3 install -r requirements.txt
        aria2c ${{ github.event.inputs.ROM_URL }} -x16 -s50 &&unzip *.zip
        python3 payload_dumper.py payload.bin & sleep 15s &&pkill python

    - name: upload boot
      run: |
        cd ~/dumper/output
        wget https://github.com/Sushrut1101/GoFile-Upload/raw/master/upload.sh >> /dev/null
        chmod +x upload.sh
        sudo apt install jq -y >> /dev/null
        mv boot.img z.img
        mv z.img ${{ github.event.inputs.BOOT_NAME }}
        ./upload.sh ${{ github.event.inputs.BOOT_NAME }}
