name: boot image dumper

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM URL'
        required: true
        default: ' '
      BOOT_NAME:
        description: 'BOOT IMAGE  NAME'
        required: true
        default: 'boot.img'
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v3
    - name: Dump boot
      run: |
        cd ~
        sudo apt install aria2
        #git clone https://github.com/vm03/payload_dumper --depth=1 dumper &&cd dumper &&pip3 install -r requirements.txt
        #
        aria2c https://downloads.sourceforge.net/project/nikgapps/Releases/Addons-T/27-Jun-2023/NikGapps-Addon-13-PixelLauncher-20230627-signed.zip?ts=gAAAAABknATNRfxZGqr2m9iN-nknRjn00WIqhZjg4msgcwHJi2jCh8I9Dv6Ct38GMDWmpQbSnlS4jgGEkuMmtoorw05gShkhCQ%3D%3D&use_mirror=webwerks&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fnikgapps%2Ffiles%2FReleases%2FAddons-T%2F27-Jun-2023%2F
       #
       # aria2c https://downloads.sourceforge.net/project/nikgapps/Releases/Addons-T/27-Jun-2023/NikGapps-Addon-13-PixelLauncher-20230627-signed.zip?ts=gAAAAABknATNRfxZGqr2m9iN-nknRjn00WIqhZjg4msgcwHJi2jCh8I9Dv6Ct38GMDWmpQbSnlS4jgGEkuMmtoorw05gShkhCQ%3D%3D&use_mirror=webwerks&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fnikgapps%2Ffiles%2FReleases%2FAddons-T%2F27-Jun-2023%2F -x16 -s50 
       # python3 payload_dumper.py payload.bin & sleep 15s &&pkill python

    - name: upload boot
      run: |
        cd ~
        wget https://github.com/Sushrut1101/GoFile-Upload/raw/master/upload.sh >> /dev/null
        chmod +x upload.sh
        sudo apt install jq -y >> /dev/null
        ./upload.sh N*.zip
